apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-k8s-job
  namespace: my-webapp
spec:
  selector:
    matchLabels:
      app: simple-k8s-job
  template:
    metadata:
      labels:
        app: nginxsimple-k8s-job
      containers:
      - name: simple-k8s-job
        image: simple-k8s-job:latest