apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: my-webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: ${ECR_ARN}:latest
        ports:
        - containerPort: 8080
