apiVersion: batch/v1
kind: Job
metadata:
  name: simple-k8s-job
  namespace: my-webapp
spec:
  template:
    metadata:
      labels:
        app: simple-k8s-job
    spec:
      containers:
      - name: simple-k8s-job
        image: ${ECR_ARN}:latest
      restartPolicy: Never
