name: "Build and push image"

on:
  workflow_dispatch:

jobs:
  build-and-push-image:
    name: "Build and push image"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    defaults:
      run:
        working-directory: "app"
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials for Infra Account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CICD_ROLE }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build tag and push app image
        id: build-tag-push-image
        run: |
          docker build -t webapp:latest .
          docker tag webapp:latest $ECR_ARN:latest
          docker push $ECR_ARN:latest



    

    