name: "Deploy DNS infra"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "dns-infra/**"
    branches:
      - main
      
env:
    TERRAFORM_VERSION: "1.6.6"

jobs:
  deploy-hosting-infra:
    name: "Deploy DNS infra"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    defaults:
      run:
        working-directory: "dns-infra"
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Configure AWS Credentials for Infra Account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CICD_ROLE}}
          aws-region: eu-west-2

      - name: Terraform Init
        id: init
        run: ls -latr; terraform init -input=false -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -no-color
        continue-on-error: false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        id: apply
        run: terraform apply -input=false -no-color -auto-approve 



