name: "Deploy App"

on:
  workflow_dispatch:

env:
    ECR_ARN: ${{ secrets.ECR_ARN }}

jobs:
  deploy-app:
    name: "Deploy App"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    defaults:
      run:
        working-directory: "app"
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials for Infra Account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CICD_ROLE }}
          aws-region: eu-west-2

      - name: Connect to cluster
        id: cluster-connect
        run: aws eks update-kubeconfig --region eu-west-2 --name webapp-eks-cluster

      - name: Deploy ingress controller
        id: deploy-ingress-controller
        run: |
          helm repo add eks https://aws.github.io/eks-charts
          helm repo update

          helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
            -n kube-system \
            --set clusterName=webapp-eks-cluster \
            --set serviceAccount.create=false \
            --set region=eu-west-2 \
            --set vpcId=$(aws ec2 describe-vpcs --filters "Name=cidr,Values=10.0.0.0/16" --query 'Vpcs[0].VpcId' --output text) \
            --set serviceAccount.name=aws-load-balancer-controller
          
      - name: Deploy app
        working-directory: "deployment-infra"
        id: deploy-app
        run: |
          kubectl apply -f namespace.yml -f service.yml -f ingress.yml
          envsubst < deployment.yml | kubectl apply -f -
          kubectl get ingress webapp-ingress -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'



    

    