name: "Deploy SSL"

on:
  workflow_dispatch:
      
env:
    DEVELOPER_EMAIL: ${{ secrets.DEVELOPER_EMAIL }}

jobs:
  deploy-ssl:
    name: "Deploy SSL"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    defaults:
      run:
        working-directory: "deployment-infra"
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials for Infra Account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CICD_ROLE}}
          aws-region: eu-west-2

      - name: Connect to cluster
        id: cluster-connect
        run: aws eks update-kubeconfig --region eu-west-2 --name webapp-eks-cluster

      - name: Deploy Cert Manager
        id: deploy-cert-manager
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
          helm install cert-manager jetstack/cert-manager \
            -n cert-manager \
            --version v1.15.0 \
            --set crds.enabled=true \
            --set serviceAccount.create=false \
            --set serviceAccount.name=cert-manager

      - name: Deploy Certificates
        id: deploy-certificates
        run: |
            envsubst < certificate.yml | kubectl apply -f -
            kubectl patch ingress webapp-ingress -n my-webapp -p '{"spec":{"tls":[{"hosts":["lev-the-dev.co.uk"],"secretName":"ssl-certificate"}]}}'



