name: "Destroy hosting infra"

on:
  workflow_dispatch:

env:
    TERRAFORM_VERSION: "1.6.6"

jobs:
  destroy-hosting-infra:
    name: "Destroy hosting infra"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    defaults:
      run:
        working-directory: "hosting-infra"
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Configure AWS Credentials for Infra Account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_PERSONAL_ADMIN_ROLE}}
          aws-region: eu-west-2

      - name: Terraform Init
        id: init
        run: ls -latr; terraform init -input=false -no-color

      - name: Terraform Plan Destroy
        id: plan-destroy
        run: terraform plan -destroy -input=false -no-color
        continue-on-error: false

      - name: Terraform destroy
        if: github.ref == 'refs/heads/main'
        id: destroy
        run: terraform destroy -input=false -no-color -auto-approve
