name: "Destroy hosting infra"

on:
  workflow_dispatch:

env:
    TERRAFORM_VERSION: "1.6.6"

jobs:
  destroy-hosting-infra:
    name: "Destroy hosting infra"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    defaults:
      run:
        working-directory: "hosting-infra"
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Configure AWS Credentials for Infra Account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CICD_ROLE}}
          aws-region: eu-west-2

      - name: Delete ECR images
        id: delete-ecr-image
        run: |
          aws ecr batch-delete-image --region eu-west-2 \
          --repository-name webapp_ecr \
          --image-ids "$(aws ecr list-images --region eu-west-2 --repository-name webapp_ecr --query 'imageIds[*]' --output json)"
        continue-on-error: false

      - name: Connect to cluster
        id: cluster-connect
        run: aws eks update-kubeconfig --region eu-west-2 --name webapp-eks-cluster

      - name: Delete kubernetes infrastructure
        id: delete-k8s
        run: |
          kubectl delete ingress webapp-ingress -n my-webapp
          helm delete aws-load-balancer-controller -n kube-system
          helm uninstall cert-manager -n cert-manager

      - name: Terraform Init
        id: init
        run: ls -latr; terraform init -input=false -no-color

      - name: Terraform Plan Destroy
        id: plan-destroy
        run: terraform plan -destroy -input=false -no-color
        continue-on-error: false

      - name: Terraform destroy
        id: destroy
        run: terraform destroy -input=false -no-color -auto-approve
